import Head from "next/head";
import Image from "next/image";
import HomeStyle from "../styles/style_component/Home.module.scss";
import Sidebar from "../components/Sidebar";
import Center from "../components/Center";
import Player from "../components/Player";
import { getSession } from "next-auth/react";

export default function Home() {
  return (
    <div className={HomeStyle.container}>
      <Head>
        <title>DealyMusic</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={HomeStyle["main--container"]}>
        <Sidebar />
        <Center />
      </main>

      <div className={HomeStyle["player--container"]}>
        <Player />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
